server:
  port: 809

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password

  jpa:

    open-in-view: false
    hibernate:
      ddl-auto: validate
